name: Cafetaria System - GCP Deployment - Services
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VM_INSTANCE_NAME: cafeteria-system-vm-services-seed
      INSTANCE_GROUP_NAME: mig-services
      VM_ZONE: asia-southeast1-a
      USERNAME: chammaofficial12
      IMAGE_NAME: cafeteria-system-vm-services-seed-boot-image-10
      REGION: asia-southeast1
      INSTANCE_TEMPLATE_NAME: cafeteria-system-vm-services-seed-template-10

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v3.0.1

      - name: Start the cafeteria-system-vm-services-seed instance
        run: |
          gcloud compute instances start ${{ env.VM_INSTANCE_NAME }} --zone=${{ env.VM_ZONE }}

      - name: Connect and Update Code
        run: |
          gcloud compute ssh ${{ env.USERNAME }}@${{ env.VM_INSTANCE_NAME }} \
            --zone=${{ env.VM_ZONE }} \
            --quiet \
            --command "
              echo 'Connected to ${{ env.VM_INSTANCE_NAME }} Successfully!' && \
              cd Cafeteria-System-Services/ && \
              git pull --recurse-submodules && \
              source ~/.bashrc && \
              mvn clean package
            "
      - name: Stop the cafeteria-system-vm-services-seed instance
        run: |
          gcloud compute instances stop ${{ env.VM_INSTANCE_NAME }} --zone=${{ env.VM_ZONE }}

      - name: Delete the boot disk of the cafeteria-system-vm-services-seed instance
        run: |
          gcloud compute images delete ${{ env.IMAGE_NAME }}
        continue-on-error: true

      - name: Create a new boot image from the updated instance
        run: |
          gcloud compute images create ${{ env.IMAGE_NAME }} \
          --source-disk=${{ env.VM_INSTANCE_NAME }} \
          --source-disk-zone=${{ env.VM_ZONE }} \
          --storage-location=${{ env.REGION }}

      - name: Update the instance template to use the new boot image
        run: |
          gcloud compute instance-groups managed rolling-action replace ${{ env.INSTANCE_GROUP_NAME }} \
          --region=${{ env.REGION }} \
          --max-unavailable=0 \
          --replacement-method=substitute \
          --max-surge=3 \
          --version=template=projects/${{ secrets.GCP_PROJECT_ID }}/regions/${{ env.REGION }}/instanceTemplates/${{ env.INSTANCE_TEMPLATE_NAME }},name=0-1774722886304
